version: '3'
services:
  server-container:
    build:
      context: ./namenode  # Build context for the server container
    container_name: server-container
    networks:
      - my-network

  client-container:
    build:
      context: ./datanode  # Build context for the client container
    container_name: client-container
    networks:
      - my-network

networks:
  my-network:
