# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 202002
    volumes:
      - type: bind
        source: "C:/users/aayus/docmnt"
        target: /data
    ports:
      - 22:22

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: "C:/users/aayus/docmnt"
        target: /data
  client:
    image: continuumio/anaconda3
    container_name: client
    volumes:
      - type: bind
        source: "C:/users/aayus/docmnt"
        target: /data
    tty: true
