version: '3'
services:
  rust-container:
    image: rust:latest
    container_name: rust_devel 
    networks:
      - my-network
    volumes:
      - type: volume
        source: mount
        target: /data
    environment:
      - CONTAINER_NAME=rust_devel
    tty: true

  

volumes:
  mount:
    external: true
    name: rust 
  
networks:
  my-network: